### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by jadamec** [oliuz/teamwork#15]
Would you be so kind to add a PHP 8 support, please?
```
oliuz/teamwork[8.0, ..., 8.0.3] require php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
- Root composer.json requires oliuz/teamwork ^8.0 -> satisfiable by oliuz/teamwork[8.0, 8.0.1, 8.0.2, 8.0.3].
```

**Comment by oliuz** [comment]
Fixed with pull request #16

**Comment by jadamec** [comment]
Could you add a new release with these change, please? I'm still getting this error. Thank you!

**Comment by oliuz** [comment]
@jadamec The release has already been created.
